### ISSUE TITLE
[BUG] 진행중인 골룸을 볼 때 스크롤이 안됨

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-co-kirikiri#77]
### 🐘 버그 사항
> 해당 버그를 **자세하게** 적어주세요!

진행중인 골룸을 볼 때 스크롤이 안돼요

### 🐘 버그 시뮬레이션
> 버그를 발견하게 된 상황을 단계별로 적어주세요.

1. 홈페이지 접속
2. 로드맵 자세히보기 접속
3. 진행중인 골룸 보기 클릭
4. 모집중인 골룸 자세히보기 클릭
5. 모달이 떴는데 스크롤이 안됨

### 🐘 원하던 상황
> 원했던 상황을 자세하게 적어주세요.
 
페이지가 잘려있는데 정보를 더 보고싶어요

### 🐘 스크린샷
버그가 발생한 상황에 대해서 사진을 찍어서 올려주세요!

![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/49794401/dedd8492-b53c-4fc2-ae61-23b56f963c89)

**Comment by Cl8D** [comment]
해결 완료됐습니다!
