### ISSUE TITLE
[BUG] 진행중인 골룸 보기에서 "자세히 보기"를 누르고 x로 끈 후 다시 "자세히 보기"를 누르면 동작하지 않아요

### ISSUE THREAD

**Issue by rawfishthelgh** [woowacourse-teams/2023-co-kirikiri#82]
### 🐘 버그 사항
> 해당 버그를 **자세하게** 적어주세요!

진행중인 골룸 보기에서 "자세히 보기"를 누르고 x로 끈 후 다시 "자세히 보기"를 누르면 동작하지 않아요
 

### 🐘 버그 시뮬레이션
> 버그를 발견하게 된 상황을 단계별로 적어주세요.

로드맵 -> 배민 코테 뿌수기 -> 자세히 보기 -> 진행중인 골룸 보기 -> 자세히 보기 -> X누름 -> 자세히 보기
-> 동작안함
 

### 🐘 원하던 상황
> 원했던 상황을 자세하게 적어주세요.

다시 자세히 보기 화면이 뜰 것으로 기대했습니다
 

### 🐘 스크린샷
> 버그가 발생한 상황에 대해서 사진을 찍어서 올려주세요!

<img width="992" alt="스크린샷 2023-08-07 오후 2 13 35" src="https://github.com/woowacourse-teams/2023-co-kirikiri/assets/79038908/220d26c4-037d-46e7-be58-f52983af1753">

**Comment by Cl8D** [comment]
해결 완료됐습니다!
