### ISSUE TITLE
[BUG] 로드맵 생성과정에서 난이도 선택

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-co-kirikiri#85]
### 🐘 버그 사항
> 해당 버그를 **자세하게** 적어주세요!

로드맵 생성과정에서 난이도를 선택했을 때 박스 내부에 값이 계속 비어있습니다.

### 🐘 버그 시뮬레이션
> 버그를 발견하게 된 상황을 단계별로 적어주세요.

1. 로그인
2. 로드맵 작성
3. 난이도 선택
4. 클릭 시 박스 내부가 비어있음

### 🐘 원하던 상황
> 원했던 상황을 자세하게 적어주세요.
 
박스 내부에 뭔가 텍스트라도 표기되었으면 좋겠어요

### 🐘 스크린샷
버그가 발생한 상황에 대해서 사진을 찍어서 올려주세요!

![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/49794401/ac8553e0-fd31-4fdd-b30e-77faa51ea08d)

**Comment by Cl8D** [comment]
해결 완료됐습니다!
