### ISSUE TITLE
[BUG] 로그인 오류

### ISSUE THREAD

**Issue by Kim0914** [woowacourse-teams/2023-co-kirikiri#86]
### 🐘 버그 사항
로그인을 정상적으로 하고, 메인 페이지로 돌아가면 우측 하단에 로그인 성공이 나옵니다.

왼쪽 하단의 로그인 버튼은 여전히 로그인 버튼으로 나오고, 로그인 버튼을 누르면 다시 로그인 페이지로 이동합니다.
 

### 🐘 버그 시뮬레이션
1. 로그인
2. 메인 페이지 리다이렉트
3. 로그인 완료 토스트 뜸
4. 왼쪽 하단에는 여전히 로그인 버튼으로 나옴
 

### 🐘 원하던 상황

로그인을 마치면 로그아웃 버튼으로 바뀌어야 할 것 같아요
 

### 🐘 스크린샷

<img width="1146" alt="image" src="https://github.com/woowacourse-teams/2023-co-kirikiri/assets/68818952/f0b40fbb-9a3f-4e49-a278-03923953cfec">

**Comment by Cl8D** [comment]
해결 완료됐습니다!
