### ISSUE TITLE
[BUG] 로드맵 생성과정에서 태그 박스

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-co-kirikiri#88]
### 🐘 버그 사항
> 해당 버그를 **자세하게** 적어주세요!
 
로드맵 생성과정에서 태그를 작성하고 엔터를 눌렀는데 난이도 박스에 상호작용이 수행됩니다.

### 🐘 버그 시뮬레이션
> 버그를 발견하게 된 상황을 단계별로 적어주세요.
 
1. 로그인
2. 로드맵 생성
3. 태그 내부에 값 작성
4. 엔터 입력 시 난이도 박스가 열리고 닫힘

### 🐘 원하던 상황
> 원했던 상황을 자세하게 적어주세요.
 
추가된 태그라는 구분을 주거나 동작이 수행되었음을 알려주는 토스트가 나오면 좋을 것 같아요

### 🐘 스크린샷
버그가 발생한 상황에 대해서 사진을 찍어서 올려주세요!
![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/49794401/3515979c-f0e1-4ec2-b9f2-f42384f96eb3)
![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/49794401/e6d4f5d0-3673-4aba-8d9c-e83e9fe6a88f)

**Comment by Cl8D** [comment]
해결 완료했습니다!
