### ISSUE TITLE
[BUG] 브라우저 창 이름이 Document 임

### ISSUE THREAD

**Issue by inyeong-kang** [woowacourse-teams/2023-co-kirikiri#90]
### 🐘 버그 사항
* 브라우저 창 이름이 Document입니다. 

### 🐘 버그 시뮬레이션
* 사이트 접속하면 계속 브라우저 창 이름이 Document입니다.
![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/81199414/48e619fb-50c7-4df7-8f12-4878f3257fa9)

### 🐘 원하던 상황
* `index.html`에서 title 태그를 변경하면 좋겠습니다!

**Comment by Cl8D** [comment]
해결 완료했습니다!
