### ISSUE TITLE
[BUG] 로드맵이 생성이 안돼요

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-co-kirikiri#91]
### 🐘 버그 사항
> 해당 버그를 **자세하게** 적어주세요!
 
해당 Request로 보냈는데 페이지가 넘어가면서 등록도 안되고 등록 정보도 사라지네요

### 🐘 버그 시뮬레이션
> 버그를 발견하게 된 상황을 단계별로 적어주세요.
 
1. 로그인
2. 로드맵 생성하기
3. 정보 작성
4. 홈페이지로 리다이렉트
5. 내 글이없음

### 🐘 원하던 상황
> 원했던 상황을 자세하게 적어주세요.

잘못된 정보가 있으면 리다이렉트하지 않고 경고창을 띄워주면 좋겠네요...

### 🐘 스크린샷
버그가 발생한 상황에 대해서 사진을 찍어서 올려주세요!

![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/49794401/a7892899-dc08-43ce-ba2c-1a4bb706340d)

```json
{
    "message": "JSON parse error: Cannot deserialize value of type `co.kirikiri.service.dto.roadmap.request.RoadmapDifficultyType` from number 5: index value outside legal index range [0..4]"
}
```

**Comment by Cl8D** [comment]
해결 완료했습니다!
