### ISSUE TITLE
골룸 생성 시 날짜 입력들이 placeholder가 아닌 것 같아요

### ISSUE THREAD

**Issue by WaiNaat** [woowacourse-teams/2023-co-kirikiri#92]
### 🐘 버그 사항

골룸 생성에 쓰는 각종 날짜들에 있는 placeholder가 미리 입력된 값처럼 보입니다
 

### 🐘 버그 시뮬레이션

그냥 골룸 생성하기 들어가면 보여요
 

### 🐘 원하던 상황

input type date나 yyyy-mm-dd처럼 확실하게 '입력을 해야 한다'는 걸 보여줬으면 좋겠어요
 

### 🐘 스크린샷

![image](https://github.com/woowacourse-teams/2023-co-kirikiri/assets/77872742/c4c27517-40be-4cb5-927d-821958499b04)

**Comment by Cl8D** [comment]
해결 완료했습니다!
